### ISSUE TITLE
Simplify permissions

### ISSUE THREAD

**Issue by seth-shaw-unlv** [mjordan/islandora_workbench_integration#24]
While attempting to add Islandora Workbench to an existing site with ratcheted down permissions I discovered that I had to grant the user's role several permissions they didn't previously have, some with security implications. They are listed below with the Permissions page label, the machine name in parentheses, and in some cases, the specific routes they apply to.

- Administer site configuration (administer site configuration)
- Content: Administer form display (administer node form display): `/entity/entity_form_display/node.dc_object.default?_format=json`
- Content: Administer fields (administer node fields): `/entity/field_config/node.dc_object.body?_format=json`
- Administer vocabularies and terms (administer taxonomy): `/term_from_uri?_format=json&uri=...` & `/term_from_authority_link?_format=json&authority_link=...`
- Taxonomy term: Administer form display (administer taxonomy_term form display): `/entity/entity_form_display/taxonomy_term.digital_projects.default?_format=json`
- Taxonomy term: Administer fields (administer taxonomy_term fields): `/entity/field_config/taxonomy_term.digital_projects.field_project_alias?_format=json`
- Administer media types (administer media types)
- Administer content types (administer nodes)

**Comment by mjordan** [comment]
@seth-shaw-unlv do we need to change anything in the module to resolve this or is this just a documentation issue?

**Comment by mjordan** [comment]
Answering my own question here... maybe this module should provide a custom permission for the routes in islandora_workbench_integration.routing.yml. Also, it is possible to export the config for a role, so we could add a pre-configured role to this module to package up all the required permissions.

**Comment by bondjimbond** [comment]
@mjordan Following up on this issue as it's becoming relevant for our sites -- is that reconfiguration of permissions feasible? We really want our sites to be able to use Workbench, but we can't give them those admin permissions.

**Comment by bondjimbond** [comment]
Following are the bare minimum permissions I have identified for a Workbench user -- this is on a site that uses Paragraphs, and therefore requires some extra stuff.

```
uuid: 9b97be8b-0d25-43ee-91d1-228b50c7a897
langcode: en
status: true
dependencies:
  config:
    - filter.format.basic_html
    - filter.format.citation_html
    - filter.format.email_html
    - filter.format.full_html
    - filter.format.restricted_html
    - media.type.3d_object
    - media.type.audio
    - media.type.document
    - media.type.embed_code
    - media.type.extracted_text
    - media.type.file
    - media.type.image
    - media.type.local_image_resource
    - media.type.oembed_remote_media
    - media.type.remote_video
    - media.type.video
    - node.type.islandora_object
    - rest.resource.oai_pmh
    - taxonomy.vocabulary.conference_events
    - taxonomy.vocabulary.corporate_body
    - taxonomy.vocabulary.country
    - taxonomy.vocabulary.culture
    - taxonomy.vocabulary.degree_names
    - taxonomy.vocabulary.discipline
    - taxonomy.vocabulary.family
    - taxonomy.vocabulary.funders
    - taxonomy.vocabulary.genre
    - taxonomy.vocabulary.geo_location
    - taxonomy.vocabulary.institution
    - taxonomy.vocabulary.language
    - taxonomy.vocabulary.local_access_conditions
    - taxonomy.vocabulary.organizational_units
    - taxonomy.vocabulary.person
    - taxonomy.vocabulary.physical_form
    - taxonomy.vocabulary.scholars
    - taxonomy.vocabulary.series_titles
    - taxonomy.vocabulary.subject
    - taxonomy.vocabulary.tags
    - taxonomy.vocabulary.temporal
    - taxonomy.vocabulary.titles
  module:
    - comment
    - embargo
    - field_permissions
    - field_ui
    - file
    - file_replace
    - filter
    - fontawesome
    - islandora
    - media
    - node
    - paragraphs
    - paragraphs_type_permissions
    - path
    - pathauto
    - rest
    - search_autocomplete
    - shortcut
    - sitemap
    - system
    - taxonomy
id: workbench_user
label: 'Workbench user'
weight: -3
is_admin: null
permissions:
  - 'access comments'
  - 'access content'
  - 'access fontawesome additional settings'
  - 'access shortcuts'
  - 'access sitemap'
  - 'administer media'
  - 'administer media fields'
  - 'administer media form display'
  - 'administer node fields'
  - 'administer node form display'
  - 'administer nodes'
  - 'administer paragraph fields'
  - 'administer paragraph form display'
  - 'administer site configuration'
  - 'administer taxonomy'
  - 'administer taxonomy_term fields'
  - 'administer taxonomy_term form display'
  - 'bulk delete aliases'
  - 'bulk update aliases'
  - 'bypass embargo access'
  - 'bypass node access'
  - 'bypass paragraphs type content access'
  - 'create 3d_object media'
  - 'create audio media'
  - 'create document media'
  - 'create embed_code media'
  - 'create extracted_text media'
  - 'create field_customcamera'
  - 'create field_display_block'
  - 'create file media'
  - 'create image media'
  - 'create islandora_object content'
  - 'create local_image_resource media'
  - 'create media'
  - 'create oembed_remote_media media'
  - 'create paragraph content faceted_subject'
  - 'create paragraph content hierarchical_geographic_subject'
  - 'create paragraph content note'
  - 'create paragraph content origin_information'
  - 'create paragraph content part'
  - 'create paragraph content perspective_camera_settings'
  - 'create paragraph content record_information'
  - 'create paragraph content related_item'
  - 'create paragraph content series'
  - 'create paragraph content title'
  - 'create remote_video media'
  - 'create terms in conference_events'
  - 'create terms in corporate_body'
  - 'create terms in country'
  - 'create terms in culture'
  - 'create terms in degree_names'
  - 'create terms in discipline'
  - 'create terms in family'
  - 'create terms in funders'
  - 'create terms in genre'
  - 'create terms in geo_location'
  - 'create terms in institution'
  - 'create terms in language'
  - 'create terms in local_access_conditions'
  - 'create terms in organizational_units'
  - 'create terms in person'
  - 'create terms in physical_form'
  - 'create terms in scholars'
  - 'create terms in series_titles'
  - 'create terms in subject'
  - 'create terms in tags'
  - 'create terms in temporal'
  - 'create terms in titles'
  - 'create url aliases'
  - 'create video media'
  - 'delete any 3d_object media'
  - 'delete any audio media'
  - 'delete any document media'
  - 'delete any embed_code media'
  - 'delete any extracted_text media'
  - 'delete any file'
  - 'delete any file media'
  - 'delete any image media'
  - 'delete any islandora_object content'
  - 'delete any local_image_resource media'
  - 'delete any media'
  - 'delete any oembed_remote_media media'
  - 'delete any remote_video media'
  - 'delete any video media'
  - 'delete media'
  - 'delete own 3d_object media'
  - 'delete own audio media'
  - 'delete own document media'
  - 'delete own embed_code media'
  - 'delete own extracted_text media'
  - 'delete own file media'
  - 'delete own files'
  - 'delete own image media'
  - 'delete own islandora_object content'
  - 'delete own local_image_resource media'
  - 'delete own oembed_remote_media media'
  - 'delete own remote_video media'
  - 'delete own video media'
  - 'delete paragraph content faceted_subject'
  - 'delete paragraph content hierarchical_geographic_subject'
  - 'delete paragraph content note'
  - 'delete paragraph content origin_information'
  - 'delete paragraph content part'
  - 'delete paragraph content perspective_camera_settings'
  - 'delete paragraph content record_information'
  - 'delete paragraph content related_item'
  - 'delete paragraph content series'
  - 'delete paragraph content title'
  - 'delete terms in conference_events'
  - 'delete terms in corporate_body'
  - 'delete terms in country'
  - 'delete terms in culture'
  - 'delete terms in degree_names'
  - 'delete terms in discipline'
  - 'delete terms in family'
  - 'delete terms in funders'
  - 'delete terms in genre'
  - 'delete terms in geo_location'
  - 'delete terms in institution'
  - 'delete terms in language'
  - 'delete terms in local_access_conditions'
  - 'delete terms in organizational_units'
  - 'delete terms in person'
  - 'delete terms in physical_form'
  - 'delete terms in scholars'
  - 'delete terms in series_titles'
  - 'delete terms in subject'
  - 'delete terms in tags'
  - 'delete terms in temporal'
  - 'delete terms in titles'
  - 'edit any 3d_object media'
  - 'edit any audio media'
  - 'edit any document media'
  - 'edit any embed_code media'
  - 'edit any extracted_text media'
  - 'edit any file media'
  - 'edit any image media'
  - 'edit any islandora_object content'
  - 'edit any local_image_resource media'
  - 'edit any oembed_remote_media media'
  - 'edit any remote_video media'
  - 'edit any video media'
  - 'edit field_customcamera'
  - 'edit field_display_block'
  - 'edit own 3d_object media'
  - 'edit own audio media'
  - 'edit own comments'
  - 'edit own document media'
  - 'edit own embed_code media'
  - 'edit own extracted_text media'
  - 'edit own field_customcamera'
  - 'edit own field_display_block'
  - 'edit own file media'
  - 'edit own image media'
  - 'edit own islandora_object content'
  - 'edit own local_image_resource media'
  - 'edit own oembed_remote_media media'
  - 'edit own remote_video media'
  - 'edit own video media'
  - 'edit terms in conference_events'
  - 'edit terms in corporate_body'
  - 'edit terms in country'
  - 'edit terms in culture'
  - 'edit terms in degree_names'
  - 'edit terms in discipline'
  - 'edit terms in family'
  - 'edit terms in funders'
  - 'edit terms in genre'
  - 'edit terms in geo_location'
  - 'edit terms in institution'
  - 'edit terms in language'
  - 'edit terms in local_access_conditions'
  - 'edit terms in organizational_units'
  - 'edit terms in person'
  - 'edit terms in physical_form'
  - 'edit terms in scholars'
  - 'edit terms in series_titles'
  - 'edit terms in subject'
  - 'edit terms in tags'
  - 'edit terms in temporal'
  - 'edit terms in titles'
  - 'manage media'
  - 'manage members'
  - 'post comments'
  - 'replace files'
  - 'restful get oai_pmh'
  - 'revert islandora_object revisions'
  - 'update any media'
  - 'update media'
  - 'update paragraph content faceted_subject'
  - 'update paragraph content hierarchical_geographic_subject'
  - 'update paragraph content note'
  - 'update paragraph content origin_information'
  - 'update paragraph content part'
  - 'update paragraph content perspective_camera_settings'
  - 'update paragraph content record_information'
  - 'update paragraph content related_item'
  - 'update paragraph content series'
  - 'update paragraph content title'
  - 'use search autocomplete'
  - 'use text format basic_html'
  - 'use text format citation_html'
  - 'use text format email_html'
  - 'use text format full_html'
  - 'use text format restricted_html'
  - 'view field_customcamera'
  - 'view field_display_block'
  - 'view islandora_object revisions'
  - 'view media'
  - 'view own field_customcamera'
  - 'view own field_display_block'
  - 'view own unpublished content'
  - 'view own unpublished media'
  - 'view paragraph content faceted_subject'
  - 'view paragraph content hierarchical_geographic_subject'
  - 'view paragraph content note'
  - 'view paragraph content origin_information'
  - 'view paragraph content part'
  - 'view paragraph content perspective_camera_settings'
  - 'view paragraph content record_information'
  - 'view paragraph content related_item'
  - 'view paragraph content series'
  - 'view paragraph content title'
  - 'view the administration theme'
```
